trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.13.0' 
  displayName: 'Install Node.js'

- script: |
    rm -rf node_modules
  displayName: 'Delete node_modules'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm run build'
